services:
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: always
        depends_on:
            - influxdb
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - web-root:/var/www/html
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
        ports:
            - '80:80'
            - '443:443'
            - '8086:8086'

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
        depends_on:
            - nginx
        command: certonly --webroot --webroot-path=/var/www/html --email ${CERT_MAIL} --agree-tos --no-eff-email -d ${URL}

    influxdb:
        image: influxdb:latest
        container_name: influxdb
        restart: always
        volumes:
            - ./influxdb.conf:/etc/influxdb/influxdb.conf
            - influxdb-data:/var/lib/influxdb2

    telegraf:
        image: telegraf:latest
        container_name: telegraf
        restart: always
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
        depends_on:
            - influxdb
        environment:
            - INFLUX_TOKEN=${INFLUX_TOKEN}

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        restart: always
        depends_on:
            - influxdb
        volumes:
            - grafana-data:/var/lib/grafana
        # environment:
        #    - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
        # this did not work, so I set the password in the UI

volumes:
    certbot-etc:
    certbot-var:
    web-root:
        driver: local
        driver_opts:
            type: none
            device: /home/app/statistics/webroot
            o: bind
    influxdb-data:
        driver: local
        driver_opts:
            type: none
            device: /home/app/statistics/influxdb-data
            o: bind
    grafana-data:
        driver: local
        driver_opts:
            type: none
            device: /home/app/statistics/grafana-data
            o: bind

